ai:
  model: phi3:mini
  ollama_url: http://localhost:11434
exchange:
  api_key: 5r6XWCYt9x8VEnpfWpYiZi0iTcqdEOmoxHdTSViajf6LjRRjjDR95q7rqncKTuTm
  api_secret: ANZqPlxu8VnrtJ6Qt0ffEA0TAjYjm6W7ytz72UQ414aSmOzV63y7lGo9HJ8IITOl
  name: binance
  testnet: true
risk_management:
  stop_loss_pct: 0.02
  trailing_activation_pct: 0.005
  trailing_callback_rate: 1.0
strategy:
  ema_filter: 20
  rsi_buy: 50
  rsi_sell: 50
trading:
  leverage: 3
  min_notional: 100
  quantity: 0.002
  risk_per_trade_pct: 1.5
  symbol: BTC/USDT
  timeframe: 15m
